# Generated by Django 2.2.3 on 2019-09-08 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSong',
            fields=[
                ('songID', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('songName', models.CharField(max_length=200)),
                ('songArtist', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Apparition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparitions.SavedSong')),
            ],
        ),
    ]
