# Generated by Django 2.2.3 on 2019-08-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparitions', '0002_auto_20190824_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songID', models.IntegerField()),
                ('songName', models.CharField(max_length=200)),
                ('songArtist', models.CharField(max_length=200)),
            ],
        ),
    ]
